name: Clean Git History
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install git-filter-repo
        run: sudo pip install git-filter-repo
      - name: Remove file from history
        run: git filter-repo --path-glob 'upload/*' --invert-paths --force
      - name: Re-add origin remote
        run: git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - name: Force push
        run: git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
