name: Clean Git History
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessário para obter todo o histórico do repositório
      - name: Install git-filter-repo
        run: |
          sudo pip install git-filter-repo
      - name: Remove files in upload directory from history
        run: |
          git filter-repo --path-glob 'upload/*' --invert-paths --force
      - name: Force push to main
        run: |
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
