name: Clean Git History
on:
  push:
    branches: [main]
  workflow_dispatch: # Adiciona gatilho para execução manual
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Atualiza para a versão mais recente
        with:
          fetch-depth: 0 # Necessário para manipular a história completa do repositório
      - name: Install git-filter-repo
        run: sudo pip install git-filter-repo
      - name: Remove file from history
        run: git filter-repo --path-glob 'upload/*' --invert-paths --force
      - name: Force push
        run: git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
